server:
  port: 8888
  servlet:
    context-path: /springboot
jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://127.0.0.1:3306/test
  username: root
  password: 1111
#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.git_repository.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true